[toolchain]
anchor_version = "1.0.2"
solana_version = "3.1.10"
package_manager = "npm"

[features]
resolution = true

[programs.devnet]
agentx_marketplace = "Ccgw6kq1PQfE5zx6EpFixNEafvRMu4udzZuNWmvzTqHA"

[programs.localnet]
agentx_marketplace = "Ccgw6kq1PQfE5zx6EpFixNEafvRMu4udzZuNWmvzTqHA"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -p agentx-marketplace"

[workspace]
types = "src/idl/"
