import type {
  Agent,
  CategoryInfo,
  Creator,
  MarketStats,
  Notification,
  PerformanceData,
  PortfolioItem,
  Proposal,
  Review,
  Transaction,
} from "@/types";
import { MARKETPLACE_PROGRAM_ADDRESS } from "@/lib/solana/marketplace";

export const MARKETPLACE_PROGRAM_ID =
  MARKETPLACE_PROGRAM_ADDRESS;

export const creators: Creator[] = [
  {
    id: "creator-orbital",
    name: "Orbital Labs",
    avatar: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=orbital",
    address: "3FgTbthafwgHnkop4XrsfrbJyrBzhKLpuVPe4rabjiJq",
    verified: true,
    agentCount: 3,
    totalEarnings: 42.8,
    rating: 4.9,
  },
  {
    id: "creator-lamport",
    name: "Lamport Research",
    avatar: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=lamport",
    address: "24BXiGu7sH8vFySvCq1pc7ASnPcJezvvyeGm6gXpxmow",
    verified: true,
    agentCount: 2,
    totalEarnings: 31.4,
    rating: 4.8,
  },
  {
    id: "creator-sunrise",
    name: "Sunrise Collective",
    avatar: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=sunrise",
    address: "3un7hADajjWTUa6YQRmSeo52DizeFneubpVMwnXsZv4i",
    verified: true,
    agentCount: 2,
    totalEarnings: 18.6,
    rating: 4.7,
  },
  {
    id: "creator-independent",
    name: "Proof of Thought",
    avatar: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=proof",
    address: "8979tGipYbi5HXb61wUQszdgiDFvPRgcvPqDoFeTJsGo",
    verified: false,
    agentCount: 1,
    totalEarnings: 4.2,
    rating: 4.6,
  },
];

function generatePerformance(
  baseRoi: number,
  baseVolume: number,
  phase: number,
): PerformanceData[] {
  const start = new Date("2026-06-15T00:00:00.000Z");

  return Array.from({ length: 31 }, (_, index) => {
    const date = new Date(start);
    date.setUTCDate(start.getUTCDate() + index);
    const wave = Math.sin((index + phase) / 4);

    return {
      date: date.toISOString().slice(0, 10),
      roi: Number((baseRoi + wave * 2.8 + index * 0.08).toFixed(2)),
      transactions: Math.round(42 + index * 2.6 + Math.abs(wave) * 24),
      successRate: Number((91 + Math.cos((index + phase) / 5) * 3).toFixed(2)),
      volume: Number((baseVolume + index * 0.18 + Math.abs(wave) * 3.5).toFixed(2)),
    };
  });
}

const commonAgentFields = {
  chain: "solana" as const,
  cluster: "devnet" as const,
  status: "active" as const,
  programId: MARKETPLACE_PROGRAM_ID,
};

export const agents: Agent[] = [
  {
    ...commonAgentFields,
    id: "sentinel-sol",
    name: "Sentinel Sol",
    description:
      "Token risk analyst that inspects mint authority, holder concentration, liquidity, and suspicious transfer patterns.",
    longDescription:
      "Sentinel Sol combines Solana RPC data with an explainable risk model. Paste a token mint to receive a structured report covering authority controls, top-holder concentration, liquidity signals, and notable account activity. It never signs or submits transactions for you.",
    category: "security",
    creator: creators[0],
    price: 0.05,
    currency: "SOL",
    pricingModel: "pay-per-use",
    auditStatus: "verified",
    verifiedOnChain: false,
    rating: 4.9,
    reviewCount: 86,
    totalUsers: 1284,
    totalTransactions: 8420,
    roi: 0,
    successRate: 98.4,
    responseTime: 680,
    image: "https://api.dicebear.com/9.x/shapes/svg?seed=sentinel-sol&backgroundColor=10b981",
    tags: ["token-risk", "mint-analysis", "holder-map", "security"],
    capabilities: ["Mint Analysis", "Holder Concentration", "Risk Scoring", "Evidence Links"],
    listingAddress: "4UGpuY7jo1ygW1JgP8r1HHP6JoF1oa6KHhLChd3Mvbn9",
    metadataUri: "ipfs://bafyagentxsentinelsol",
    demoPrompts: [
      "Analyze the SOL token mint and explain the authority risks",
      "What holder concentration should make me cautious?",
      "Create a pre-trade security checklist",
    ],
    createdAt: "2026-03-08T09:00:00.000Z",
    updatedAt: "2026-07-14T08:30:00.000Z",
    performance: generatePerformance(0, 18, 1),
  },
  {
    ...commonAgentFields,
    id: "yield-pilot",
    name: "Yield Pilot",
    description:
      "Compares lending, liquid staking, and liquidity vault opportunities across the Solana ecosystem.",
    longDescription:
      "Yield Pilot turns protocol rates into a risk-aware allocation brief. It compares opportunities from Kamino, Marinade, Jito, Orca, and Meteora, highlights lockups and liquidity risks, and produces a rebalance proposal that remains user-signed.",
    category: "defi",
    creator: creators[0],
    price: 0.2,
    currency: "SOL",
    pricingModel: "subscription",
    auditStatus: "verified",
    verifiedOnChain: false,
    rating: 4.8,
    reviewCount: 64,
    totalUsers: 936,
    totalTransactions: 6240,
    roi: 18.7,
    successRate: 95.1,
    responseTime: 820,
    image: "https://api.dicebear.com/9.x/shapes/svg?seed=yield-pilot&backgroundColor=14f195",
    tags: ["yield", "staking", "lending", "allocation"],
    capabilities: ["Protocol Comparison", "Risk Budgeting", "Rebalance Plans", "Yield Monitoring"],
    listingAddress: "6XysSG9QNr4MDZiFVhSydc3KZXYFDXXGCuSpUnqV2y52",
    metadataUri: "ipfs://bafyagentxyieldpilot",
    demoPrompts: [
      "Compare low-risk SOL yield opportunities",
      "Build a conservative 10 SOL allocation",
      "Explain liquid staking depeg risk",
    ],
    createdAt: "2026-02-12T10:15:00.000Z",
    updatedAt: "2026-07-13T11:10:00.000Z",
    performance: generatePerformance(16, 26, 2),
  },
  {
    ...commonAgentFields,
    id: "jupiter-scout",
    name: "Jupiter Scout",
    description:
      "Trade-planning assistant that compares routes, price impact, liquidity depth, and execution risk before a swap.",
    longDescription:
      "Jupiter Scout prepares an execution brief before you swap. It explains route quality, price impact, likely slippage, liquidity depth, and token-specific warnings. The final transaction is always reviewed and signed in the user's wallet.",
    category: "trading",
    creator: creators[1],
    price: 0.08,
    currency: "SOL",
    pricingModel: "pay-per-use",
    auditStatus: "verified",
    verifiedOnChain: false,
    rating: 4.8,
    reviewCount: 51,
    totalUsers: 748,
    totalTransactions: 11980,
    roi: 12.4,
    successRate: 96.8,
    responseTime: 540,
    image: "https://api.dicebear.com/9.x/shapes/svg?seed=jupiter-scout&backgroundColor=06b6d4",
    tags: ["swap", "slippage", "routing", "liquidity"],
    capabilities: ["Route Comparison", "Price Impact", "Slippage Planning", "Transaction Preview"],
    listingAddress: "582mdL4A8p3LFHSxfGxcqXRZZhfvVYqZVF2dnUD3N9cQ",
    metadataUri: "ipfs://bafyagentxjupiterscout",
    demoPrompts: [
      "What should I inspect before swapping a thin-liquidity token?",
      "Explain price impact versus slippage",
      "Build a safe execution checklist for a 5 SOL swap",
    ],
    createdAt: "2026-04-20T14:00:00.000Z",
    updatedAt: "2026-07-14T06:20:00.000Z",
    performance: generatePerformance(11, 34, 3),
  },
  {
    ...commonAgentFields,
    id: "nft-lens",
    name: "NFT Lens",
    description:
      "Collection research assistant for floor depth, trait distribution, wallet concentration, and comparable sales.",
    longDescription:
      "NFT Lens organizes marketplace and collection signals into a transparent research report. It summarizes floor depth, rare-trait sales, holder concentration, and comparable collections without presenting speculative outputs as guaranteed valuations.",
    category: "nft",
    creator: creators[2],
    price: 0.1,
    currency: "SOL",
    pricingModel: "one-time",
    auditStatus: "pending",
    verifiedOnChain: false,
    rating: 4.6,
    reviewCount: 37,
    totalUsers: 412,
    totalTransactions: 2860,
    roi: 8.9,
    successRate: 91.7,
    responseTime: 920,
    image: "https://api.dicebear.com/9.x/shapes/svg?seed=nft-lens&backgroundColor=ec4899",
    tags: ["nft", "traits", "floor-depth", "sales"],
    capabilities: ["Collection Overview", "Trait Analysis", "Sales Comparables", "Holder Mapping"],
    listingAddress: "28ytwj37xUc58Twd6CnQVBHhwaSSkhN4ViYEi9vQDqKg",
    metadataUri: "ipfs://bafyagentxnftlens",
    demoPrompts: [
      "How do I judge whether an NFT floor is liquid?",
      "Explain trait rarity without overfitting",
      "Create a collection due-diligence checklist",
    ],
    createdAt: "2026-05-02T09:45:00.000Z",
    updatedAt: "2026-07-12T17:00:00.000Z",
    performance: generatePerformance(8, 12, 4),
  },
  {
    ...commonAgentFields,
    id: "portfolio-pulse",
    name: "Portfolio Pulse",
    description:
      "Wallet analytics agent that explains concentration, protocol exposure, drawdown, and rebalance options.",
    longDescription:
      "Portfolio Pulse converts a wallet snapshot into an understandable risk report. It groups holdings by asset and protocol, flags concentration, estimates drawdown exposure, and proposes user-controlled rebalancing scenarios.",
    category: "analytics",
    creator: creators[1],
    price: 0.15,
    currency: "SOL",
    pricingModel: "subscription",
    auditStatus: "verified",
    verifiedOnChain: false,
    rating: 4.7,
    reviewCount: 44,
    totalUsers: 615,
    totalTransactions: 4210,
    roi: 14.1,
    successRate: 94.2,
    responseTime: 760,
    image: "https://api.dicebear.com/9.x/shapes/svg?seed=portfolio-pulse&backgroundColor=3b82f6",
    tags: ["portfolio", "exposure", "drawdown", "rebalance"],
    capabilities: ["Exposure Mapping", "Drawdown Scenarios", "Rebalance Plans", "Wallet Summary"],
    listingAddress: "B2UdwoNBiKG2ePCcHEMQijRQmkufrZzFGYpdmhoe3RnM",
    metadataUri: "ipfs://bafyagentxportfoliopulse",
    demoPrompts: [
      "How should I measure protocol concentration?",
      "Design a balanced Solana portfolio risk report",
      "Explain drawdown scenarios in plain English",
    ],
    createdAt: "2026-03-29T12:00:00.000Z",
    updatedAt: "2026-07-14T09:10:00.000Z",
    performance: generatePerformance(13, 20, 5),
  },
  {
    ...commonAgentFields,
    id: "dao-brief",
    name: "DAO Brief",
    description:
      "Governance copilot that summarizes proposals, surfaces tradeoffs, and compares voting outcomes.",
    longDescription:
      "DAO Brief turns long governance proposals into neutral, cited summaries. It identifies affected parameters, treasury impact, stakeholder tradeoffs, and unresolved questions while leaving the final vote entirely to the wallet owner.",
    category: "governance",
    creator: creators[2],
    price: 0,
    currency: "SOL",
    pricingModel: "free",
    auditStatus: "verified",
    verifiedOnChain: false,
    rating: 4.7,
    reviewCount: 28,
    totalUsers: 804,
    totalTransactions: 3620,
    roi: 0,
    successRate: 97.2,
    responseTime: 610,
    image: "https://api.dicebear.com/9.x/shapes/svg?seed=dao-brief&backgroundColor=f59e0b",
    tags: ["dao", "governance", "proposals", "treasury"],
    capabilities: ["Proposal Summary", "Tradeoff Analysis", "Treasury Impact", "Voting Context"],
    listingAddress: "3FgTbthafwgHnkop4XrsfrbJyrBzhKLpuVPe4rabjiJq",
    metadataUri: "ipfs://bafyagentxdaobrief",
    demoPrompts: [
      "Summarize the risks in a treasury diversification proposal",
      "What questions should delegates ask before voting?",
      "Compare quorum and approval thresholds",
    ],
    createdAt: "2026-04-06T08:30:00.000Z",
    updatedAt: "2026-07-11T15:20:00.000Z",
    performance: generatePerformance(0, 8, 6),
  },
  {
    ...commonAgentFields,
    id: "social-radar",
    name: "Social Radar",
    description:
      "Research agent that separates recurring community themes from short-lived hype and coordinated noise.",
    longDescription:
      "Social Radar clusters public discussion into durable themes, tracks changes in sentiment, and marks low-confidence or coordinated signals. It is designed for research context rather than automatic trading decisions.",
    category: "social",
    creator: creators[3],
    price: 0.04,
    currency: "SOL",
    pricingModel: "pay-per-use",
    auditStatus: "unaudited",
    verifiedOnChain: false,
    rating: 4.5,
    reviewCount: 19,
    totalUsers: 286,
    totalTransactions: 1880,
    roi: 6.3,
    successRate: 86.4,
    responseTime: 1040,
    image: "https://api.dicebear.com/9.x/shapes/svg?seed=social-radar&backgroundColor=8b5cf6",
    tags: ["sentiment", "community", "signals", "research"],
    capabilities: ["Theme Clustering", "Sentiment Change", "Noise Detection", "Research Briefs"],
    listingAddress: "24BXiGu7sH8vFySvCq1pc7ASnPcJezvvyeGm6gXpxmow",
    metadataUri: "ipfs://bafyagentxsocialradar",
    demoPrompts: [
      "How can I distinguish durable interest from short-term hype?",
      "Build a social-signal confidence rubric",
      "Explain coordinated posting risk",
    ],
    createdAt: "2026-06-01T11:00:00.000Z",
    updatedAt: "2026-07-10T13:50:00.000Z",
    performance: generatePerformance(5, 7, 7),
  },
  {
    ...commonAgentFields,
    id: "airdrop-navigator",
    name: "Airdrop Navigator",
    description:
      "Eligibility and activity planner that prioritizes legitimate protocol usage without multi-wallet farming automation.",
    longDescription:
      "Airdrop Navigator tracks public campaign criteria, estimates the cost of legitimate participation, and keeps a transparent activity checklist. It explicitly avoids Sybil automation and never asks for seed phrases or custody.",
    category: "utility",
    creator: creators[0],
    price: 0.06,
    currency: "SOL",
    pricingModel: "one-time",
    auditStatus: "verified",
    verifiedOnChain: false,
    rating: 4.6,
    reviewCount: 31,
    totalUsers: 522,
    totalTransactions: 3040,
    roi: 10.2,
    successRate: 92.8,
    responseTime: 700,
    image: "https://api.dicebear.com/9.x/shapes/svg?seed=airdrop-navigator&backgroundColor=a855f7",
    tags: ["eligibility", "campaigns", "checklist", "anti-sybil"],
    capabilities: ["Criteria Tracking", "Cost Planning", "Activity Checklist", "Sybil Risk Warnings"],
    listingAddress: "3un7hADajjWTUa6YQRmSeo52DizeFneubpVMwnXsZv4i",
    metadataUri: "ipfs://bafyagentxairdropnavigator",
    demoPrompts: [
      "Create a legitimate protocol participation checklist",
      "How should I estimate opportunity cost for a campaign?",
      "Explain common Sybil red flags",
    ],
    createdAt: "2026-05-18T10:00:00.000Z",
    updatedAt: "2026-07-12T07:40:00.000Z",
    performance: generatePerformance(9, 11, 8),
  },
];

export const reviews: Review[] = [
  {
    id: "review-1",
    agentId: "sentinel-sol",
    userId: "wallet-1",
    userName: "breakpoint.sol",
    userAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=breakpoint",
    rating: 5,
    comment: "The report separated hard on-chain evidence from model interpretation. That made the risk score much easier to trust.",
    createdAt: "2026-07-10T14:30:00.000Z",
  },
  {
    id: "review-2",
    agentId: "yield-pilot",
    userId: "wallet-2",
    userName: "staked.sol",
    userAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=staked",
    rating: 5,
    comment: "Useful comparison of liquidity and smart-contract risk instead of just ranking the highest APY.",
    createdAt: "2026-07-08T09:15:00.000Z",
  },
  {
    id: "review-3",
    agentId: "jupiter-scout",
    userId: "wallet-3",
    userName: "routefinder.sol",
    userAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=routefinder",
    rating: 4,
    comment: "Clear pre-trade checklist and a good explanation of why price impact changed between routes.",
    createdAt: "2026-07-05T18:45:00.000Z",
  },
  {
    id: "review-4",
    agentId: "portfolio-pulse",
    userId: "wallet-4",
    userName: "balanced.sol",
    userAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=balanced",
    rating: 5,
    comment: "It caught that three positions were all exposed to the same protocol even though the token names were different.",
    createdAt: "2026-07-02T11:20:00.000Z",
  },
];

export const transactions: Transaction[] = [
  {
    id: "tx-1",
    type: "purchase",
    agentId: "yield-pilot",
    agentName: "Yield Pilot",
    amount: 0.2,
    token: "SOL",
    from: "28ytwj37xUc58Twd6CnQVBHhwaSSkhN4ViYEi9vQDqKg",
    to: creators[0].address,
    signature: "4vHbvoT5uxZ7RmqEBKH8Ve7KCB4Cg1qfXHDrSt1geTPqrvhzVuZi2kWbh17heveSZL1MXbExBavKbviruUNDchs6",
    status: "confirmed",
    createdAt: "2026-07-14T10:30:00.000Z",
  },
  {
    id: "tx-2",
    type: "run",
    agentId: "sentinel-sol",
    agentName: "Sentinel Sol",
    amount: 0.05,
    token: "SOL",
    from: "28ytwj37xUc58Twd6CnQVBHhwaSSkhN4ViYEi9vQDqKg",
    to: creators[0].address,
    signature: "5hPvs3HWsh5x7HRZXiKhMRiZXuANekQgv1YuWH7VTgC3babTSeNcZLznyHWVQrzYRV5UVG7wVkiEMy9tbcQapp4K",
    status: "confirmed",
    createdAt: "2026-07-14T08:05:00.000Z",
  },
  {
    id: "tx-3",
    type: "payout",
    agentId: "jupiter-scout",
    agentName: "Jupiter Scout",
    amount: 1.84,
    token: "SOL",
    from: MARKETPLACE_PROGRAM_ID,
    to: creators[1].address,
    signature: "3YKu6FpeyMneDzw5wZHnUhtW8aNe2MbCrAaQgF65qXbffZdp98nRbYe8aaFc1xBYqNKKLLAYtbu1jE7jdK3s41mc",
    status: "confirmed",
    createdAt: "2026-07-13T16:00:00.000Z",
  },
  {
    id: "tx-4",
    type: "register",
    agentId: "portfolio-pulse",
    agentName: "Portfolio Pulse",
    amount: 0.01,
    token: "SOL",
    from: creators[1].address,
    to: MARKETPLACE_PROGRAM_ID,
    signature: "58qnnLhgeUUYa2Ntr1eYxXG7Ai5goh744sWVdutxaUimWLMbrMMKzZQ1ZUe1XkcPWAn14SUhD9jz9rQLqjKi5B8c",
    status: "confirmed",
    createdAt: "2026-07-12T09:15:00.000Z",
  },
];

export const notifications: Notification[] = [
  {
    id: "notification-1",
    type: "success",
    title: "Access granted",
    message: "Yield Pilot is now available in your playground.",
    read: false,
    createdAt: "2026-07-14T10:31:00.000Z",
  },
  {
    id: "notification-2",
    type: "warning",
    title: "Risk signal changed",
    message: "Sentinel Sol detected a mint-authority change in a watched token.",
    read: false,
    createdAt: "2026-07-14T08:30:00.000Z",
  },
  {
    id: "notification-3",
    type: "info",
    title: "New proposal",
    message: "Protocol fee proposal #12 is open for voting.",
    read: true,
    createdAt: "2026-07-13T09:00:00.000Z",
  },
];

export const proposals: Proposal[] = [
  {
    id: "proposal-12",
    title: "Set marketplace protocol fee to 8%",
    description: "Reduce the protocol fee from 10% to 8% for the next growth season while preserving the creator payout in the same atomic settlement.",
    proposer: "breakpoint.sol",
    proposerAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=breakpoint",
    status: "active",
    votesFor: 428000,
    votesAgainst: 126000,
    totalVotes: 554000,
    quorum: 700000,
    startDate: "2026-07-10T00:00:00.000Z",
    endDate: "2026-07-18T00:00:00.000Z",
    category: "parameter",
  },
  {
    id: "proposal-11",
    title: "Fund independent agent security reviews",
    description: "Allocate 5,000 USDC from the community treasury to reproducible security and prompt-safety reviews for the ten most-used agents.",
    proposer: "auditdao.sol",
    proposerAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=auditdao",
    status: "active",
    votesFor: 365000,
    votesAgainst: 84000,
    totalVotes: 449000,
    quorum: 700000,
    startDate: "2026-07-12T00:00:00.000Z",
    endDate: "2026-07-20T00:00:00.000Z",
    category: "treasury",
  },
  {
    id: "proposal-10",
    title: "Require evidence links in security-agent output",
    description: "Add a marketplace policy requiring security agents to separate RPC evidence, model inference, and unresolved uncertainty.",
    proposer: "proof.sol",
    proposerAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=proof",
    status: "passed",
    votesFor: 802000,
    votesAgainst: 46000,
    totalVotes: 848000,
    quorum: 700000,
    startDate: "2026-06-28T00:00:00.000Z",
    endDate: "2026-07-06T00:00:00.000Z",
    category: "listing",
  },
];

export const portfolio: PortfolioItem[] = [
  {
    agentId: "yield-pilot",
    agentName: "Yield Pilot",
    agentImage: agents[1].image,
    category: "defi",
    purchasePrice: 0.2,
    currentValue: 0.24,
    roi: 18.7,
    purchaseDate: "2026-06-18T10:00:00.000Z",
  },
  {
    agentId: "portfolio-pulse",
    agentName: "Portfolio Pulse",
    agentImage: agents[4].image,
    category: "analytics",
    purchasePrice: 0.15,
    currentValue: 0.17,
    roi: 14.1,
    purchaseDate: "2026-06-25T14:00:00.000Z",
  },
  {
    agentId: "airdrop-navigator",
    agentName: "Airdrop Navigator",
    agentImage: agents[7].image,
    category: "utility",
    purchasePrice: 0.06,
    currentValue: 0.07,
    roi: 10.2,
    purchaseDate: "2026-07-01T08:00:00.000Z",
  },
];

export const marketStats: MarketStats = {
  totalAgents: agents.length,
  totalVolume: 184.6,
  activeUsers: 2156,
  totalTransactions: agents.reduce((total, agent) => total + agent.totalTransactions, 0),
  avgRoi: 11.7,
};

export const categories: CategoryInfo[] = [
  { id: "defi", name: "DeFi", icon: "Coins", description: "Yield, lending, liquidity, and protocol research", agentCount: 1, color: "#14f195" },
  { id: "trading", name: "Trading", icon: "TrendingUp", description: "Execution planning, routing, and liquidity analysis", agentCount: 1, color: "#06b6d4" },
  { id: "nft", name: "NFT", icon: "Image", description: "Collection research, traits, and comparable sales", agentCount: 1, color: "#ec4899" },
  { id: "analytics", name: "Analytics", icon: "BarChart3", description: "Wallet exposure, performance, and risk reporting", agentCount: 1, color: "#3b82f6" },
  { id: "security", name: "Security", icon: "Shield", description: "Token, account, and transaction risk analysis", agentCount: 1, color: "#10b981" },
  { id: "social", name: "Social", icon: "MessageCircle", description: "Community themes, sentiment, and noise detection", agentCount: 1, color: "#8b5cf6" },
  { id: "governance", name: "Governance", icon: "Vote", description: "Proposal summaries and governance tradeoffs", agentCount: 1, color: "#f59e0b" },
  { id: "utility", name: "Utility", icon: "Wrench", description: "Research checklists and workflow assistants", agentCount: 1, color: "#a855f7" },
];
